### PR TITLE
Update prettier related packages to 2.0.

### PR DESCRIPTION
**Pull request by rwjblue**
See details in https://prettier.io/blog/2020/03/21/2.0.0.html.

Closes #34 
Closes #38

### CODE REVIEW

**Comment by hjdivad** [comment]
nyxbot merge when green

**Comment by hjdivad** [comment]
nyxbot shouldn't you have this command by now 😭

**Comment by hjdivad** [comment]
okay the reason our recordings keep getting invalidated is because the request bodies don't match because they contain the date the test is run on as part of the issue title

**Comment by hjdivad** [comment]
@rwjblue i was going to rebase this on top of #32, dropping my commit that adds a recording, but #32 is red due to some issues with volta installing certain nodes.

Something to dig into.

**Comment by rwjblue** [comment]
Rebased on top of #32, dropped extra recording, 🤞.

**Pull request merged**
